language: java

env:
  global:
    - secure: "VgzgkHpv8GQtVighZP+Fnkeaj08Abk8c+HJePEkO+0c1aoeL0Lwt6yUwXrMlPhgBndLi9foDZV1PH1xVxLlnj5u5GA8hNoNY4cOxjvEpD3E9MQ0gsdKmclMsoodJpY6YQ67FMexW6IVOHxkHcbEFm7ylcobmhyyX+MHujir980s="
    - secure: "GdbZFkBJYt7nuAg8VJytyFFwW/HPpH/kcXXtdjH7Dw5dF/rw1QlBkMCrzVPYv1QgaBW6eprdWQ1OeSi8A4puK/jMGyAxcLVjmop1167MUQjt1C9HuY1HjMiwCrTpbdHchPSQd37cg++sbJ9AXaKdfRxLZ/knMKLtcH/p8d8DHWQ="

before_install:
  - export TERM=dumb
  - chmod +x scripts/install_android_sdk.sh
  - ./scripts/install_android_sdk.sh
  - source ~/.android-sdk-installer/env
  - echo no | android create avd --force -n test -t android-19
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - ./gradlew -q assemble

script:
  - ./gradlew check
  - wait_for_emulator
  - ./gradlew -PpreDex=false connectedCheck

after_success:
  - chmod +x scripts/deploy_to_maven.sh
  - ./scripts/deploy_to_maven.sh
  - ./gradlew integrationTest
