language: android

android:
  components:
    - build-tools-20.0.0
    - android-19
    - android-10
    - extra-android-m2repository
    - sys-img-x86-android-10
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    - secure: "VgzgkHpv8GQtVighZP+Fnkeaj08Abk8c+HJePEkO+0c1aoeL0Lwt6yUwXrMlPhgBndLi9foDZV1PH1xVxLlnj5u5GA8hNoNY4cOxjvEpD3E9MQ0gsdKmclMsoodJpY6YQ67FMexW6IVOHxkHcbEFm7ylcobmhyyX+MHujir980s="
    - secure: "GdbZFkBJYt7nuAg8VJytyFFwW/HPpH/kcXXtdjH7Dw5dF/rw1QlBkMCrzVPYv1QgaBW6eprdWQ1OeSi8A4puK/jMGyAxcLVjmop1167MUQjt1C9HuY1HjMiwCrTpbdHchPSQd37cg++sbJ9AXaKdfRxLZ/knMKLtcH/p8d8DHWQ="
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-10  ANDROID_ABI=x86

before_install:
  - export TERM=dumb

  # Create and run emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - ./gradlew -q assemble

script:
  # JavaVM tests
  - ./gradlew --continue check
  # Android tests
  - ./scripts/wait_emulator || exit 1
  - adb shell input keyevent 82 &
  - ./gradlew --continue -PpreDex=false :images:conCheck :goro:conCheck :net:conCheck :async:conCheck :async-rx:conCheck

after_success:
  - chmod +x scripts/deploy_to_maven.sh
  - ./scripts/deploy_to_maven.sh
  - ./gradlew integrationTest
